# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 35a9e5833a9a4ea7c7e96f4e52fc153bfbca144e1b9bf592d78d839092149bdb9268848cd6baef2d52b8dafc5a0017ea415b02718a35ef85f487f5779c2a4051

test:
  secret_key_base: ca9194be9b347ca509f8cb1933e0e50d83af935ab6f281ecc70ca135d3913036097799d216feeb845d5402423c5aab008b068eba5a61f8d5bda2061db2990d2e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
